/**********************************************************************************************************************
 * \file OurCan_message.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

 #ifndef OURCAN_MESSAGE_H_
 #define OURCAN_MESSAGE_H_
 
 /*********************************************************************************************************************/
 /*-----------------------------------------------------Includes------------------------------------------------------*/
 #include "OurCan_signal.h"
 
 /*********************************************************************************************************************/
 
 /*********************************************************************************************************************/
 /*------------------------------------------------------Macros-------------------------------------------------------*/
 // CANDB ID �젙�쓽
 #define VCU_Vehicle_Status_ID 0x01
 #define VCU_Parking_Status_ID 0x12
 #define VCU_Vehicle_Engine_Status_ID 0x02
 #define VCU_ParkingLane_Request_ID 0x0C
 #define VCU_Camera_ID 0x0B
 #define VCU_Exiting_Status_ID 0x13
 #define SCU_Obstacle_Detection_ID 0x28
 #define CGW_OTA_File_Size_ID 0x5C
 #define CGW_OTA_File_Data_ID 0x5D
 #define CGW_OTA_Control_ID 0x59
 
 #define CGW_OTA_Update_Request_ID 0x5A
 #define CGW_OTA_Update_State_ID 0x5B
 #define CGW_Vehicle_Status_ID 0x42
 
 #define CGW_Engine_ID 0x49
 #define CGW_Move_ID 0x4A
 #define CGW_Auto_Parking_Request_ID 0x51
 #define CGW_Off_Request_ID 0x4B
 
 //#define CTRL_OTA_Update_Confirm_ID 201
 
 #define CCU_Cordi_data1_ID 0xA1
 #define CCU_Cordi_data2_ID 0xA2
 #define CCU_RightAngle_detect_ID 0xA0
#define CCU_ParkingAngle_detect_ID 0xA3
 #define CCU_Parking_Complete_ID 0xA4
 #define CTRL_Engine_ID 0xC9
 #define CTRL_Move_ID 0xCA
 #define CTRL_Auto_Parking_Request_ID 0xD1
 
 #define CTRL_OTA_Update_Confirm_ID 0xD9
 
 #define CTRL_Off_Request_ID 0xCB
 
 
 
 // CANDB �겕湲� �젙�쓽
 #define VCU_Vehicle_Status_Size 2
 #define VCU_Parking_Status_Size 1
 #define VCU_Vehicle_Engine_Status_Size 1
 #define VCU_ParkingLane_Request_Size 1
 #define VCU_Camera_Size 1
 #define VCU_Exiting_Status_Size 1
 #define SCU_Obstacle_Detection_Size 1
 #define CGW_OTA_File_Size_Size 4
 #define CGW_OTA_File_Data_Size 8
 #define CGW_OTA_Control_Size 8
 
 #define CGW_OTA_Update_Request_Size 1
 #define CGW_OTA_Update_State_Size 1
 #define CGW_Vehicle_Status_Size 2
 
 #define CGW_Engine_Size 1
 #define CGW_Move_Size 2
 #define CGW_Auto_Parking_Request_Size 1
 #define CGW_Off_Request_Size 1
 
 #define CCU_Cordi_data1_Size 6
 #define CCU_Cordi_data2_Size 7
 #define CCU_RightAngle_detect_Size 1
#define CCU_ParkingAngle_detect_Size 1
 #define CCU_Parking_Complete_Size 1
 #define CTRL_Engine_Size 1
 #define CTRL_Move_Size 2
 #define CTRL_Auto_Parking_Request_Size 1
 
 #define CTRL_OTA_Update_Confirm_Size 1
 
 #define CTRL_Off_Request_Size 1
 
 /*********************************************************************************************************************/
 
 /*********************************************************************************************************************/
 /*-------------------------------------------------Global variables--------------------------------------------------*/
 /*********************************************************************************************************************/
 
 /*********************************************************************************************************************/
 /*-------------------------------------------------Data Structures---------------------------------------------------*/
 
 
 /*********************************************************************************************************************/
 
 /*********************************************************************************************************************/
 /*--------------------------------------------Private Variables/Constants--------------------------------------------*/
 /*********************************************************************************************************************/
 
 /*********************************************************************************************************************/
 /*------------------------------------------------Function Prototypes------------------------------------------------*/
 /*********************************************************************************************************************/
 
 void Serialize_VCU_Vehicle_Status_Msg(uint16* serialized, const VCU_Vehicle_Status_Msg *data);
 void Serialize_VCU_Parking_Status_Msg(uint8* serialized, const VCU_Parking_Status_Msg *data);
 void Serialize_VCU_Vehicle_Engine_Status_Msg(uint8* serialized, const VCU_Vehicle_Engine_Status_Msg *data);
 void Serialize_VCU_Exiting_Status_Msg(uint8* serialized, const VCU_Exiting_Status_Msg *data);
 void Serialize_VCU_ParkingLane_Request_Msg(uint8* serialized, const VCU_ParkingLane_Request_Msg *data);
 void Serialize_VCU_Camera_Msg(uint8* serialized, const VCU_Camera_Msg *data);
 void Serialize_SCU_Obstacle_Detection_Msg(uint8* serialized, const SCU_Obstacle_Detection_Msg *data);
 
 //void Serialize_CCU_Cordi_data1_Msg(uint64* serialized, const CCU_Cordi_data1_Msg* data);
 
 void Deserialize_CGW_OTA_File_Size_Msg(uint32* serialized, CGW_OTA_File_Size_Msg *data);
 void Deserialize_CGW_OTA_File_Data_Msg(uint64* serialized, CGW_OTA_File_Data_Msg *data);
 void Deserialize_CGW_OTA_Control_Msg(uint64* serialized, CGW_OTA_Control_Msg *data);
 void Deserialize_CCU_Cordi_data1_Msg(uint64* serialized, CCU_Cordi_data1_Msg *data);
 void Deserialize_CCU_Cordi_data2_Msg(uint64* serialized, CCU_Cordi_data2_Msg *data);
 void Deserialize_CCU_RightAngle_detect_Msg(uint8* serialized, CCU_RightAngle_detect_Msg* data);
 void Deserialize_CCU_ParkingAngle_detect_Msg(uint8* serialized, CCU_ParkingAngle_detect_Msg* data);
 void Deserialize_CCU_Parking_Complete_Msg(uint8* serialized, CCU_Parking_Complete_Msg* data);
 
 void Deserialize_CGW_Engine_Msg(uint8* serialized, CGW_Engine_Msg *data);
 void Deserialize_CGW_Move_Msg(uint16* serialized, CGW_Move_Msg *data);
 void Deserialize_CGW_Auto_Parking_Request_Msg(uint8* serialized, CGW_Auto_Parking_Request_Msg *data);
 void Deserialize_CGW_Off_Request_Msg(uint8* serialized, CGW_Off_Request_Msg *data);
 
 void Deserialize_CTRL_Engine_Msg(uint8* serialized, CTRL_Engine_Msg *data);
 void Deserialize_CTRL_Move_Msg(uint16* serialized, CTRL_Move_Msg *data);
 void Deserialize_CTRL_Auto_Parking_Request_Msg(uint8* serialized, CTRL_Auto_Parking_Request_Msg *data);
 void Deserialize_CTRL_Off_Request_Msg(uint8* serialized, CTRL_Off_Request_Msg *data);
 
 #endif /* OURCAN_MESSAGE_H_ */
 
