/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 #include "Ifx_Types.h"
 #include "IfxCpu.h"
 #include "IfxScuWdt.h"
 #include "IfxCpu_reg.h"
 #include "Cpu/CStart/IfxCpu_CStart.h"

 #include "SysSe/Bsp/Bsp.h"

 #define APPLICATION_A_ADDRESS 0x80064000 /*Partition A address */
 #define APPLICATION_B_ADDRESS 0x8014000 /*Partition B address */
 #define BOOT_FLAG_ADDR BKP->DR1 /*Boot flag address*/

 #define BOOT_FLAG_A 0x01 /* Partition A activate */
 #define BOOT_FLAG_B 0x02 /* Partition B activate */

 IfxCpu_syncEvent g_cpuSyncEvent = 0;

 uint32 g_appStack;
 uint32 g_res;
 uint32 current_lcx;
 uint32 current_psw;

 typedef void (*pFunction)(void);
 void JumpToApplication(uint32 appAddress);


 void core0_main(void)
 {
     IfxCpu_enableInterrupts();

     g_res = __mfcr(CPU_PCXI);

     /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
      * Enable the watchdogs and service them periodically if it is required
      */
     IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
     IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

     /* Wait for CPU sync event */
     IfxCpu_emitEvent(&g_cpuSyncEvent);
     IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

     waitTime(300000000); // 3초

     JumpToApplication(APPLICATION_A_ADDRESS);

     while(1)
     {
     }
 }


 void JumpToApplication(uint32 appAddress)
{
     //Jump to application
     __asm("ja (0x80064020)"); // BOOTA의 reset 주소
     // 호출하는 주소로 포맷팅 or 조건문으로 A / B 점프

     //Should never reach here
     while(1) { }
 }
