/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "TC275_LCD_16x2.h"
#include "Controller_Logic.h"
//#include "SPI_CPU.h"
#include "Driver_Stm.h"
//#include "ASCLIN_Shell_UART.h"
#include "ASCLIN_UART.h"
#include "Message.h"
#include "Data_process.h"

//#define DEBUG_PRINT

typedef struct
{
//    uint32 u32nuCnt1ms;
    uint32 u32nuCnt10ms;
    uint32 u32nuCnt100ms;
    uint32 u32nuCnt1000ms;

} Taskcnt;

void AppScheduling(void);
//void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

Taskcnt stTestCnt;

IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    IfxCpu_setCoreMode(&MODULE_CPU1, IfxCpu_CoreMode_run);

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    Driver_Stm_Init();

    init_LCD();
    init_Controller();

//    initPeripherals();
#ifdef DEBUG_PRINT
    initShellInterface();
#endif
//    init_ASCLIN_UART();
    while(1)
    {
//        runShellInterface();
        AppScheduling();

//        if(receive_flag == RECEIVE_COMPLETED)
//        {
//
//            Command[ORDER_RECEIVE]();
//            receive_flag = RECEIVE_WAIT;
//        }

    }
}

//void AppTask1ms(void)
//{
//    stTestCnt.u32nuCnt1ms++;
//    {
//
//    }
//}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;

    {

    }
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;

    {

        Control_Current_State();
#ifdef DEBUG_PRINT
        myprintf("%d\n\r",
                msg.move_msg.signal.control_steering_angle);
//                msg.off_req_msg.signal.auto_exit_request);
#endif
#ifdef PERIOD_VER
        Command[ORDER_ENGINE]();
        Command[ORDER_MOVE]();
        Command[ORDER_OFF_REQ]();
        Command[ORDER_OTA_UDT_CFM]();
        Command[ORDER_AUTO_PRK_REQ]();
#endif
#ifndef PERIOD_VER
        if(msg.engine_msg.signal.control_engine == 1)
        {
            Command[ORDER_MOVE]();
        }
#endif

    }

}

void AppTask1000ms(void)
{

    stTestCnt.u32nuCnt1000ms++;
    {

//        send_receive_ASCLIN_UART_message();
//        send_receive_ASCLIN_UART_message();
    }
}

void AppScheduling(void)
{

//    if (stSchedulingInfo.u8nuScheduling1msFlag == 1u)
//    {
//        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
//
//        AppTask1ms();
//
//        if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
//        {
    if (stSchedulingInfo.u8nuScheduling10msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling10msFlag = 0u;
        AppTask10ms();

        if (stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if (stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
