/**********************************************************************************************************************
 * \file Message.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef INC_MESSAGE_H_
#define INC_MESSAGE_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Platform_Types.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define ID_ENGINE_MSG               0xC9
#define ID_MOVE_MSG                 0xCA
#define ID_AUTO_PARK_REQ_MSG        0xD1
#define ID_OTA_UDT_CFM_MSG          0xD9
#define ID_OFF_REQ_MSG              0xCB
#define ID_CGW_OTA_UDT_REQ_MSG      0x5A
#define ID_CGW_OTA_UDT_STATE_MSG    0x5B
#define ID_CGW_PRK_STATUS_MSG       0x52
#define ID_CGW_VHC_STATUS_MSG       0x42



/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data typedef structures---------------------------------------------------*/
typedef struct
{
  uint8 control_engine:1;
}engine_signal;

typedef struct
{
  uint8 msgId;  // 메시지 ID (1바이트)
  engine_signal signal;
}CTRL_Engine;


typedef struct
{
    uint8 control_accel:1;
    uint8 control_brake:1;
    sint8 control_steering_angle:7;
    uint8 control_transmission:2;
}move_signal;
typedef struct
{
    uint8 msgId;  // 메시지 ID (1바이트)
    move_signal signal;

}CTRL_Move;

typedef struct
{
  uint8 auto_parking:1;
}p_r_signal;

typedef struct
{
  uint8 msgId;  // 메시지 ID (1바이트)
  p_r_signal signal;
}CTRL_Auto_Parking_Request;

typedef struct
{
  uint8 ota_confirm:1;
}OUC_signal;

typedef struct
{
  uint8 msgId;  // 메시지 ID (1바이트)
  OUC_signal signal;
}CTRL_OTA_Update_Confirm;
//

typedef struct
{
  uint8 alert_request:1;
  uint8 auto_exit_request:1;
}Off_req_signal;

typedef struct
{
  uint8 msgId;  // 메시지 ID (1바이트)
  Off_req_signal signal;
}CTRL_Off_Request;

typedef struct
{
    uint8 ota_update_request:1;

}OUR_signal;
typedef struct
{
    uint8 msgId;  // 메시지 ID (1바이트)
    OUR_signal signal;

}CGW_OTA_Update_Request;

typedef struct
{
    uint8 ota_update_progress:8;
}OUS_signal;
typedef struct
{
    uint8 msgId;  // 메시지 ID (1바이트)
    OUS_signal signal;

}CGW_OTA_Update_State_Msg;

typedef struct
{
    uint8 parking_status:2;

}PS_signal;
typedef struct
{
    uint8 msgId;  // 메시지 ID (1바이트)
    PS_signal signal;

}CGW_Parking_Status_Msg;

typedef struct
{
    uint8 vehicle_velocity:7;
    sint8 vehicle_steering_angle:7;
    uint8 vehicle_transmission:2;
}VS_signal;
typedef struct
{
    uint8 msgId;  // 메시지 ID (1바이트)
    VS_signal signal;

}CGW_Vehicle_Status_Msg;

typedef struct
{
  CTRL_Engine engine_msg;
  CTRL_Move move_msg;
  CTRL_Auto_Parking_Request auto_park_req_msg;
  CTRL_OTA_Update_Confirm ota_udt_cfm_msg;
  CTRL_Off_Request off_req_msg;
  CGW_OTA_Update_Request cgw_ota_udt_req_msg;
  CGW_OTA_Update_State_Msg cgw_ota_udt_state_msg;
  CGW_Parking_Status_Msg cgw_prk_status_msg;
  CGW_Vehicle_Status_Msg cgw_vhc_status_msg;
}Message;

extern Message msg;

//typedef struct
//{
// uint8 engine_flag:1;
// uint8 move_flag:1;
// uint8 auto_park_req_flag:1;
// uint8 ota_update_confirm_flag:1;
// uint8 off_req_flag:1;
//}Flag;

//#pragma pack()
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
void structToByteArray(void *certain_msg, uint8 *buffer, unsigned long long size);
void byteArrayToStruct(uint8 *buffer, void *certain_msg, unsigned long long size);

/*********************************************************************************************************************/


#endif /* INC_MESSAGE_H_ */
