/**********************************************************************************************************************
 * \file GPIO_LED_Button.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *********************************************************************************************************************/
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "LED_Buzzer.h"
#include "Ifx_Types.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define LED     &MODULE_P00,1   /* Port pin for the LED     */
#define BUZZER2  &MODULE_P00,9
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxGtm_Tom_Pwm_Config g_tomConfig;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriver;
uint32 uPeriod = (10000000/329.724);/* Timer Driver structure                       */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

int cnt_alarm=0;
int alarm_request=0;
int led=1;
int buzzer=1;
/* Function to configure the port pins for the push button and the LED */

void init_LED_Buzzer(void)
{
    IfxPort_setPinModeOutput(LED,IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  //led
    IfxPort_setPinLow(LED);

    IfxPort_setPinModeOutput(BUZZER2,IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);  //led
    IfxPort_setPinLow(BUZZER2);

}

/* Depending on the the state of the "BUTTON" port pin, the LED is turned on or off */
void LED_Buzzer_Blink(void)
{
    if (led==0)
    {
        IfxPort_setPinLow(LED);
        IfxPort_setPinLow(BUZZER2);

        led=1;
    }
    else
    {
        IfxPort_setPinHigh(LED);
        IfxPort_setPinHigh(BUZZER2);
        led=0;
    }
}

void Buzzer(void)
{
    if (buzzer==0)
    {
        IfxPort_setPinLow(BUZZER2);

        buzzer=1;
    }
    else
    {
        IfxPort_setPinHigh(BUZZER2);
        buzzer=0;
    }
}

void FindCar_Plz(void){
    if (alarm_request==1){
        if (cnt_alarm <=5)
        {
            LED_Buzzer_Blink();
            //Buzzer();

        }

        else if (cnt_alarm>5){
            //setDutyCycleB(0);
            //buzzer=0;
            led=1;
            alarm_request=0;
            cnt_alarm=0;
        }
    }
}

void Obstacle_Alarm(void){

}

