/**********************************************************************************************************************
 * \file Logger.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Logger.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static IfxAsclin_Asc uart;
static uint8 ascTxBuffer[ASC_TX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
static uint8 ascRxBuffer[ASC_RX_BUFFER_SIZE + sizeof(Ifx_Fifo) + 8];
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void initUartLogger(void) {
    // UART 설정 구조체
    IfxAsclin_Asc_Config ascConfig;

    // 기본 설정으로 초기화
    IfxAsclin_Asc_initModuleConfig(&ascConfig, &MODULE_ASCLIN3);

    // 통신 속도 설정
    ascConfig.baudrate.baudrate = UART_BAUDRATE;

    // 버퍼 설정
    ascConfig.txBuffer = &ascTxBuffer;
    ascConfig.txBufferSize = ASC_TX_BUFFER_SIZE;
    ascConfig.rxBuffer = &ascRxBuffer;
    ascConfig.rxBufferSize = ASC_RX_BUFFER_SIZE;

    // Pins 설정
    const IfxAsclin_Asc_Pins pins = {
        .cts        = NULL_PTR,                   // CTS pin not used
        .ctsMode    = IfxPort_InputMode_pullUp,
        .rx         = &IfxAsclin3_RXD_P32_2_IN ,  // RX pin
        .rxMode     = IfxPort_InputMode_pullUp,
        .rts        = NULL_PTR,                   // RTS pin not used
        .rtsMode    = IfxPort_OutputMode_pushPull,
        .tx         = &IfxAsclin3_TX_P15_7_OUT,  // TX pin
        .txMode     = IfxPort_OutputMode_pushPull,
        .pinDriver  = IfxPort_PadDriver_cmosAutomotiveSpeed1
    };
    ascConfig.pins = &pins;

    // UART 초기화
    IfxAsclin_Asc_initModule(&uart, &ascConfig);
}


void sendDataLog(const char* data) {
    IfxAsclin_Asc_write(&uart, data, (Ifx_SizeT)strlen(data), TIME_INFINITE);
    // 개행 문자 추가
    const char newline[] = "\r\n";
    IfxAsclin_Asc_write(&uart, newline, (Ifx_SizeT)strlen(newline), TIME_INFINITE);
}


void logNumericData(const char* label, sint32 value) {
    char buffer[50];
    sprintf(buffer, "%s: %.2f", label, value);
    sendDataLog(buffer);
}
/*********************************************************************************************************************/
