/**********************************************************************************************************************
 * \file OurCan_message.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "OurCan.h"
#include "Platform_Types.h"
#include <string.h>
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

// Serialize
// VCU TX

void Serialize_VCU_Vehicle_Status_Msg(uint16* serialized, const VCU_Vehicle_Status_Msg *data) {
    *serialized |= (uint16)(data->vehicle_velocity & 0x7F);               // 7비트
    *serialized |= (uint16)((sint16)data->vehicle_steering_angle & 0x7F) << 7;    // 7비트
    *serialized |= (uint16)(data->vehicle_transmission & 0x03) << 14;     // 2비트
}

void Serialize_VCU_Parking_Status_Msg(uint8* serialized, const VCU_Parking_Status_Msg *data) {
    *serialized |= (data->parking_status & 0x03);                 // 2비트
}

void Serialize_VCU_Vehicle_Engine_Status_Msg(uint8* serialized, const VCU_Vehicle_Engine_Status_Msg *data) {
    *serialized |= (data->vehicle_engine_status & 0x01);          // 1비트
}

void Serialize_VCU_Camera_Msg(uint8* serialized, const VCU_Camera_Msg *data) {
    *serialized |= (data->camera_num & 0x03);                     // 2비트
}

void Serialize_SCU_Obstacle_Detection_Msg(uint8* serialized, const SCU_Obstacle_Detection_Msg *data) {
    *serialized |= (data->F_obstacle & 0x01);                     // 1비트
    *serialized |= (data->B_obstacle & 0x01) << 1;                // 1비트
    *serialized |= (data->R_obstacle & 0x01) << 2;                // 1비트
    *serialized |= (data->L_obstacle & 0x01) << 3;                // 1비트
}


////
void Serialize_CCU_Cordi_data1_Msg(uint64* serialized, const CCU_Cordi_data1_Msg *data) {
    *serialized = 0;
    *serialized |= (uint64)(data->cordi_data_y1 & 0x7FF);       // 11비트
    *serialized |= (uint64)((sint64)data->cordi_data_x1 & 0x3FF) << 11; // 10비트
    *serialized |= (uint64)(data->cordi_data_y2 & 0x7FF) << 21; // 11비트
    *serialized |= (uint64)((sint64)data->cordi_data_x2 & 0x3FF) << 32; // 10비트
    *serialized |= (uint64)(data->using_camera & 0x03) << 42;   // 2비트

//    *serialized = 0;
//    *serialized |= (data->cordi_data_y1 & 0x7FF);       // 11비트
//    *serialized |= (data->cordi_data_x1 & 0x3FF) << 11; // 10비트
//    *serialized |= (data->cordi_data_y2 & 0x7FF) << 21; // 11비트
//    *serialized |= (data->cordi_data_x2 & 0x3FF) << 32; // 10비트
//    *serialized |= (data->using_camera & 0x03) << 42;   // 2비트

}


//VCU RX

void Deserialize_CGW_OTA_File_Size_Msg(uint32* serialized, CGW_OTA_File_Size_Msg *data) {
    data->ota_file_size = *serialized;
}

void Deserialize_CGW_OTA_File_Data_Msg(uint64* serialized, CGW_OTA_File_Data_Msg *data) {
    data->ota_file_data = *serialized;
}

void Deserialize_CGW_OTA_Control_Msg(uint64* serialized, CGW_OTA_Control_Msg *data) {
    data->ota_control = *serialized;
}

void Deserialize_CCU_Cordi_data1_Msg(uint64* serialized, CCU_Cordi_data1_Msg *data) {
    data->cordi_data_y1 = (*serialized >> 0) & 0x7FF;       // 11비트
    data->cordi_data_x1 = (*serialized >> 11) & 0x3FF;      // 10비트
    data->cordi_data_y2 = (*serialized >> 21) & 0x7FF;      // 11비트
    data->cordi_data_x2 = (*serialized >> 32) & 0x3FF;      // 10비트
    data->using_camera = (*serialized >> 42) & 0x03;        // 2비트
//    data->cordi_data_y1 = (*serialized >> 0) & 0x7FF;       // 11비트 (부호 없음)
//    data->cordi_data_x1 = (sint64)((*serialized >> 11) & 0x3FF); // 10비트 (부호 있음)
//    if (data->cordi_data_x1 & 0x200) { // 부호 비트 확인
//        data->cordi_data_x1 |= ~0x3FF; // 부호 확장
//    }
//    data->cordi_data_y2 = (*serialized >> 21) & 0x7FF;      // 11비트 (부호 없음)
//    data->cordi_data_x2 = (sint64)((*serialized >> 32) & 0x3FF); // 10비트 (부호 있음)
//    if (data->cordi_data_x2 & 0x200) { // 부호 비트 확인
//        data->cordi_data_x2 |= ~0x3FF; // 부호 확장
//    }
//    data->using_camera = (*serialized >> 42) & 0x03;        // 2비트 (부호 없음)
}

void Deserialize_CGW_Engine_Msg(uint8* serialized, CGW_Engine_Msg *data) {
    data->control_engine = (*serialized >> 0) & 0x01;       // 1비트
}

void Deserialize_CGW_Move_Msg(uint16* serialized, CGW_Move_Msg *data) {
    data->control_accel = (*serialized >> 0) & 0x01;        // 1비트
    data->control_brake = (*serialized >> 1) & 0x01;        // 1비트
    data->control_steering_angle = (*serialized >> 2) & 0x7F; // 7비트
    data->control_transmission = (*serialized >> 9) & 0x03; // 2비트
}

void Deserialize_CGW_Auto_Parking_Request_Msg(uint8* serialized, CGW_Auto_Parking_Request_Msg *data) {
    data->auto_parking = (*serialized >> 0) & 0x01;         // 1비트
}

void Deserialize_CGW_Off_Request_Msg(uint8* serialized, CGW_Off_Request_Msg *data) {
    data->alert_request = (*serialized >> 0) & 0x01;        // 1비트
    data->auto_exit_request = (*serialized >> 1) & 0x01;    // 1비트
}


void Deserialize_CCU_Cordi_data2_Msg(uint64* serialized, CCU_Cordi_data2_Msg *data) {
    data->cordi_data_y3 = (*serialized >> 0) & 0x7FF;       // 11비트
    data->cordi_data_x3 = (*serialized >> 11) & 0x3FF;      // 10비트
    data->cordi_data_y4 = (*serialized >> 21) & 0x7FF;      // 11비트
    data->cordi_data_x4 = (*serialized >> 32) & 0x3FF;      // 10비트
    data->using_camera = (*serialized >> 42) & 0x03;        // 2비트
//    data->cordi_data_y3 = (*serialized >> 0) & 0x7FF;       // 11비트 (부호 없음)
//    data->cordi_data_x3 = (sint64)((*serialized >> 11) & 0x3FF); // 10비트 (부호 있음)
//    if (data->cordi_data_x3 & 0x200) { // 부호 비트 확인
//        data->cordi_data_x3 |= ~0x3FF; // 부호 확장
//    }
//    data->cordi_data_y4 = (*serialized >> 21) & 0x7FF;      // 11비트 (부호 없음)
//    data->cordi_data_x4 = (sint64)((*serialized >> 32) & 0x3FF); // 10비트 (부호 있음)
//    if (data->cordi_data_x4 & 0x200) { // 부호 비트 확인
//        data->cordi_data_x4 |= ~0x3FF; // 부호 확장
//    }
//    data->using_camera = (*serialized >> 42) & 0x03;        // 2비트 (부호 없음)
}

void Deserialize_CTRL_Engine_Msg(uint8* serialized, CTRL_Engine_Msg *data) {
    data->control_engine = (*serialized >> 0) & 0x01;       // 1비트
}

void Deserialize_CTRL_Move_Msg(uint16* serialized, CTRL_Move_Msg *data) {
    data->control_accel = (*serialized >> 0) & 0x01;        // 1비트
    data->control_brake = (*serialized >> 1) & 0x01;        // 1비트
    data->control_steering_angle = (*serialized >> 2) & 0x7F; // 7비트
    data->control_transmission = (*serialized >> 9) & 0x03; // 2비트
}

void Deserialize_CTRL_Auto_Parking_Request_Msg(uint8* serialized, CTRL_Auto_Parking_Request_Msg *data) {
    data->auto_parking = (*serialized >> 0) & 0x01;         // 1비트
}

void Deserialize_CTRL_Off_Request_Msg(uint8* serialized, CTRL_Off_Request_Msg *data) {
    data->alert_request = (*serialized >> 0) & 0x01;        // 1비트
    data->auto_exit_request = (*serialized >> 1) & 0x01;    // 1비트
}





