/**********************************************************************************************************************
 * \file Controller_ADC.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Controller_Logic.h"
#include "Message.h"
#include "Delay.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
ButtonState g_btn_adc_result = BS_NOTHING;
sint8 g_SH_adc_result = 0;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
Vadc_t g_LCD_Btn;
Vadc_t g_Steering_Wheel;

IfxVadc_Adc_ChannelConfig adc_channel_config_btn[8];
IfxVadc_Adc_Channel   adc_channel_btn[8];
uint32 adc_result_buffer[8] = {0u,};

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
static void init_Vadc_Config(Vadc_t * Vadc_val){

    /* VADC Configuration */

    /* create configuration */
    IfxVadc_Adc_Config adcConfig;
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);

    /* initialize module */
    IfxVadc_Adc_initModule(&Vadc_val->vadc, &adcConfig);

    /* create group config */
    IfxVadc_Adc_GroupConfig adcGroupConfig;
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &Vadc_val->vadc);

    /* with group  */
    adcGroupConfig.groupId = Vadc_val->adcGroupId;
    adcGroupConfig.master  = adcGroupConfig.groupId;

    /* enable scan source */
    adcGroupConfig.arbiter.requestSlotScanEnabled = TRUE;

    /* enable auto scan */
    adcGroupConfig.scanRequest.autoscanEnabled = TRUE;

    /* enable all gates in "always" mode (no edge detection) */
    adcGroupConfig.scanRequest.triggerConfig.gatingMode =
                                    IfxVadc_GatingMode_always;

    /* initialize the group */
    /*IfxVadc_Adc_Group adcGroup;*/    //declared globally
    IfxVadc_Adc_initGroup(&Vadc_val->adcGroup, &adcGroupConfig);

    /*channel init*/
    IfxVadc_Adc_initChannelConfig(&adc_channel_config_btn[Vadc_val->chnIx],
                                            &Vadc_val->adcGroup);

    adc_channel_config_btn[Vadc_val->chnIx].channelId      =
            (IfxVadc_ChannelId)(Vadc_val->chnIx);
    adc_channel_config_btn[Vadc_val->chnIx].resultRegister =
            (IfxVadc_ChannelResult)(Vadc_val->chnIx); /* use dedicated result register */

    /* initialize the channel */
    IfxVadc_Adc_initChannel(&adc_channel_btn[Vadc_val->chnIx],
                    &adc_channel_config_btn[Vadc_val->chnIx]);

    /* add to scan */
    unsigned channels = (1 << adc_channel_config_btn[Vadc_val->chnIx].channelId);
    unsigned mask     = channels;
    IfxVadc_Adc_setScan(&Vadc_val->adcGroup, channels, mask);
}
/*
 * @brief  adc 변환을 시작하는 함수
 */
static void start_btn_conversion(void)
{
    /* start autoscan */
    IfxVadc_Adc_startScan(&g_LCD_Btn.adcGroup);
}

static sint8 mapValue(float input, float in_min, float in_max, float out_min, float out_max) {
    return (sint8)((input - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
}

static sint8 convert_SH_data(uint32 analogValue) {
    float voltage = analogValue * (5.0 / 4095.0);

    sint8 steeringAngle = mapValue(voltage, 0.0, 5.0, -45, 45);

//    sprintf(str,"%d / %.2f",steeringAngle,voltage);
//    LCD1602_print(str);

    return steeringAngle;
}

/*
 * @brief  아날로그 결과값을 데시벨로 변환하는 함수
 * @param  analogValue: obtain으로 얻은 adc 결과값
 * @return
 * @note
 */
static ButtonState convert_btn_data(uint32 analogValue) {
    float voltage = analogValue * (5.0 / 4095.0);
    ButtonState BS = BS_NOTHING;
    if(voltage < 0.5)
    {
        BS= BS_UP;
    }

    else if(voltage < 1.0)
    {
        BS= BS_DOWN;
    }

    else if(voltage < 2.0)
    {
        BS= BS_LEFT;
    }

    else if(voltage < 3.0)
    {
        BS= BS_RIGHT;
    }
    else if(voltage < 4.0)
    {
        BS= BS_SELECT;
    }


    return BS;
}

static uint32 obtain_Vadc_data(uint32 chnIx)
{

    Ifx_VADC_RES conversionResult; /* wait for valid result */

    /* check results */
    do
    {
        conversionResult = IfxVadc_Adc_getResult(&adc_channel_btn[chnIx]);
    } while (!conversionResult.B.VF);

    adc_result_buffer[chnIx] = conversionResult.B.RESULT;
    return adc_result_buffer[chnIx];
}
/*
 * @brief  button 데이터(A8, SAR4.6)초기화 함수
 */
void init_Steering_Wheel(){
    // 4_6
    g_Steering_Wheel.adcGroupId = IfxVadc_GroupId_4;
    g_Steering_Wheel.chnIx = 6;
    init_Vadc_Config(&g_Steering_Wheel);

}
/*
 * @brief  button 데이터(A8, SAR4.7)초기화 함수
 */
void init_Btn_Adc(void)
{
    //4_7
    g_LCD_Btn.adcGroupId = IfxVadc_GroupId_4;
    g_LCD_Btn.chnIx = 7;
    init_Vadc_Config(&g_LCD_Btn);
}







/*
 * @brief  센서 데이터를 읽어오는 함수
 * @return uint32: adc 결과값
 */


uint8 get_SH_data(void)
{
//    start_btn_conversion(); // 같은 채널임
//    MicroSecDelay(200); // adc 변환 시간 확보
    uint32 adc_result =  obtain_Vadc_data(g_Steering_Wheel.chnIx);

    //디버깅을 위한 부분
    g_SH_adc_result = convert_SH_data(adc_result);
    //if(g_SH_adc_result <= 45)
    msg.move_msg.signal.control_steering_angle = g_SH_adc_result;
    return 1;
}


/*
 * @brief  ButtonState를 받아오는 함수
 * @return float: 데시별 결과값
 * @note   2ms 이상의 주기에서 수행해야함
 */
uint8 get_btn_data(void) {
    start_btn_conversion();
    MicroSecDelay(200); // adc 변환 시간 확보
    uint32 adc_result = obtain_Vadc_data(g_LCD_Btn.chnIx);

    //디버깅을 위한 부분
    g_btn_adc_result = convert_btn_data(adc_result);

    //btn 인풋 받을때 같이 받기
    get_SH_data();
    return 1;
}



/*********************************************************************************************************************/
