/**********************************************************************************************************************
 * \file Controller_OTA_State.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Controller_Logic.h"
#include "TC275_LCD_16x2.h"
#include "IfxFlash.h"
#include <string.h>
#include <stdio.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

#define DFLASH_START_ADDR     0xAF000000  // 데이터 플래시 시작 주소

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
OTAUpdateState g_current_ota_update;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static char str[20];
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void Show_OTA_Confirm_State()
{
    LCD1602_clear();
    LCD1602_1stLine();
    LCD1602_print(" SUBSCRIBE NOW? ");
    LCD1602_2ndLine();
    LCD1602_print("    Y      N    ");
    static OtaCursor now_cursor = OTA_CURSOR_LEFT;
    static OtaMode prev_state = OTA_NOTHING;
    LCD1602_setCursor(2, now_cursor);
    switch (g_btn_adc_result)
    {
        case (OTA_LEFT):
        {
            if(prev_state != OTA_LEFT)
            {
                prev_state = OTA_LEFT;
                now_cursor = OTA_CURSOR_LEFT;

                // 명령 송신
                //msg.move_msg.signal.control_transmission = dir_state;
            }
            break;
        }
        case (OTA_RIGHT):
        {
            if(prev_state != OTA_RIGHT)
            {
                prev_state = OTA_RIGHT;
                now_cursor = OTA_CURSOR_RIGHT;

                // 명령 송신
                //msg.move_msg.signal.control_transmission = dir_state;
            }
            break;
        }
        case (OTA_SELECT):
        {
            if(prev_state != OTA_SELECT)
            {
                prev_state = OTA_SELECT;
                LCD1602_clear();
                LCD1602_1stLine();
                if(now_cursor == OTA_CURSOR_LEFT)
                {
                    //yes
                    LCD1602_print("SERVICE LOADING");
                    g_current_ctrl_state = CTRL_OTA;
                    g_isreq_reject = false;
                }
                else
                {
                    //no

                    LCD1602_print("CANCEL SUBSCRIBE");
                    g_current_ctrl_state = CTRL_OFF;
                    g_isreq_reject = true;
                }
                LCD1602_2ndLine();
                LCD1602_loading();

                // 명령 송신
                //msg.move_msg.signal.control_transmission = dir_state;
            }
            break;
        }
        default :
        {
            prev_state = OTA_NOTHING;
        }
    }
}

void Show_OTA_State()
{
    LCD1602_clear();


    // 첫째 줄 - 코멘트
    LCD1602_1stLine();

    LCD1602_print("OTA UPDATE");
//    LCD1602_loading();


    // 둘째 줄
    LCD1602_2ndLine();

//    uint8 print_progress = local_udt_state_sig.ota_update_progress;
    sprintf(str, "%02u%%[", ((local_udt_state_sig.ota_update_progress) < 100 ?
            local_udt_state_sig.ota_update_progress : 99));


    LCD1602_print(str);

    LCD1602_print_percent_img(local_udt_state_sig.ota_update_progress);
    LCD1602_print("]");
    LCD1602_setCursor(1, 11);
    LCD1602_loading_nodelay();

    if(local_udt_state_sig.ota_update_progress ==  100 )
    {
        g_current_ota_update = OTA_UPDATED;
        writeFlash(OTA_UPDATED);

        LCD1602_clear();
        LCD1602_1stLine();
        LCD1602_print("OTA UPDATE DONE!");
        LCD1602_2ndLine();
        LCD1602_print("REBOOT");
        LCD1602_loading();

        g_current_ctrl_state = CTRL_OFF;
    }
}






 void writeFlash(OTAUpdateState ota_info)
 {
     uint32 writeData = (uint32)ota_info;

     uint16 password;

     // 1. 섹터 지우기
     password = IfxScuWdt_getSafetyWatchdogPassword();
     IfxScuWdt_clearSafetyEndinit(password);
     IfxFlash_eraseMultipleSectors(DFLASH_START_ADDR, 1);  // 1개 섹터 지우기
     IfxScuWdt_setSafetyEndinit(password);

     // 지우기 완료 대기
     IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);

     // 2. 데이터 쓰기
     // 페이지 모드 진입
     IfxFlash_enterPageMode(DFLASH_START_ADDR);
     IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);

     // 데이터 로드 (8바이트 단위로 로드해야 함)
     IfxFlash_loadPage2X32(DFLASH_START_ADDR, writeData, 0);

     // 페이지 쓰기
     password = IfxScuWdt_getSafetyWatchdogPassword();
     IfxScuWdt_clearSafetyEndinit(password);
     IfxFlash_writePage(DFLASH_START_ADDR);
     IfxScuWdt_setSafetyEndinit(password);

     // 쓰기 완료 대기
     IfxFlash_waitUnbusy(0, IfxFlash_FlashType_D0);

     // 3. 데이터 읽기

 }
/*********************************************************************************************************************/

 void readFlash(void)
{
     uint32 *readData;
     readData = (uint32*)DFLASH_START_ADDR;
     g_current_ota_update = *readData;
}
