/**********************************************************************************************************************
 * \file Controller_Logic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include <stdio.h>

#include "Controller_Logic.h"
#include "ASCLIN_UART.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
LCDButtonVadc g_LCD_Btn;
IfxVadc_Adc_ChannelConfig adc_channel_config_btn[8];
IfxVadc_Adc_Channel   adc_channel_btn[8];
uint32 adc_result_btn[8] = {0u,};
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
char str[20];
ButtonState g_btn_adc_result = BS_NOTHING;
ControllerState g_current_ctrl_state = CTRL_OFF;
OTAUpdateState g_current_ota_update = OTA_UPDATED;

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void Show_OTA_State()
{
    LCD1602_clear();
    get_btn_data();

    // 첫째 줄 - 코멘트
    LCD1602_1stLine();


    sprintf(str, "SERVICE LOAD");

    LCD1602_print(str);
    LCD1602_loading();


    // 둘째 줄
    LCD1602_2ndLine();

    uint8 ota_pct = 50;


    sprintf(str, "OTA-%02d%%", ota_pct);

    LCD1602_print(str);

    LCD1602_print_percent_img(ota_pct);
}

void Show_Drive_State()
{
    LCD1602_clear();
    get_btn_data();

    static DriveDir dir_state = DIR_D;
    static DriveModeState ms_state = MS_DRIVE;
    static DriveMode prev_state = DRIVE_NOTHING;
    LCD1602_1stLine();

    switch(g_btn_adc_result){
    case (DRIVE_ACCEL):
    {
        sprintf(str, "GOGOGO");
        //SPI송신
        prev_state = DRIVE_ACCEL;
        break;
    }
    case (DRIVE_BRAKE):
    {
        sprintf(str, "SLOW SLOW");
        //SPI송신
        prev_state = DRIVE_BRAKE;
        break;
    }
    case (DRIVE_POWEROFF):
    {
        LCD1602_clear();
        LCD1602_1stLine();
        sprintf(str, "POWER OFF");
        LCD1602_print(str);
        LCD1602_loading();
        if(prev_state != DRIVE_POWEROFF){
            prev_state = DRIVE_POWEROFF;
            //파워 off 동작 로직
            g_current_ctrl_state = CTRL_OFF;
            //SPI송신

        }
        break;
    }
    case (DRIVE_MODE):
    {
        sprintf(str, "DIRECTION CHANGE");

        if(prev_state != DRIVE_MODE){
            prev_state = DRIVE_MODE;
            //모드 변경 로직
            //SPI송신
            if(dir_state == DIR_D)
            {
                dir_state = DIR_R;
            }
            else if(dir_state == DIR_R)
            {
                dir_state = DIR_D;
            }

        }
        break;
    }
    // **********OTA시 활성화*********************//
    case (DRIVE_SERVICE):
    {
        LCD1602_clear();
        if(g_current_ota_update == OTA_UPDATED)
        {


            if(prev_state != DRIVE_SERVICE){
                prev_state = DRIVE_SERVICE;
                if(ms_state == MS_DRIVE)
                {
                    ms_state = MS_AUTO_PARKING;
                    dir_state = DIR_P;

                    LCD1602_1stLine();
                    sprintf(str, "AUTO PARKING");
                    LCD1602_print(str);
                    LCD1602_loading();
                }
                else if(ms_state == MS_AUTO_PARKING)
                {
                    ms_state = MS_DRIVE;
                    dir_state = DIR_D;

                    LCD1602_1stLine();
                    sprintf(str, "DRIVING MODE");
                    LCD1602_print(str);
                    LCD1602_loading();
                }


            }
        }
        else
        {
            LCD1602_1stLine();
            sprintf(str, "DO SUBSCRIBE TO");
            LCD1602_print(str);
            LCD1602_2ndLine();
            sprintf(str, "USE AUTO PARKING");
            LCD1602_print(str);
            LCD1602_loading();

        }



        break;
    }
    //******************************************//
    default :
    {
        sprintf(str, "");
        prev_state = BS_NOTHING;
    }
    }

    LCD1602_print(str);


    LCD1602_2ndLine();
    if(dir_state == DIR_D)
    {
        sprintf(str, "D");
    }
    else if(dir_state == DIR_R)
    {
        sprintf(str, "R");
    }
    else if(dir_state == DIR_P)
    {
        sprintf(str, "P");
    }
    LCD1602_print(str);
    if(ms_state == MS_DRIVE)
    {
        sprintf(str, "     DRIVE MODE");
    }
    else if(ms_state == MS_AUTO_PARKING)
    {
        sprintf(str, "   PARKING MODE");
    }
    LCD1602_print(str);
}

void Show_Off_State()
{
    LCD1602_clear();
    get_btn_data();

    // 첫째 줄 - 코멘트
    LCD1602_1stLine();



    LCD1602_print("PWR");
    LCD1602_print_picture(PIC_ROTATED_LINE);
    LCD1602_print("VEHICLE FIND");


    // 둘째 줄
    LCD1602_2ndLine();

    LCD1602_print_picture(PIC_LEFT_DOWN_ARROW);

    LCD1602_print("ON");

    LCD1602_print_picture(PIC_DOWN_ARROW);
    LCD1602_print(" ");
    LCD1602_print_picture(PIC_DOWN_ARROW);

    LCD1602_print("AUTO LEAVE");



    get_btn_data();

    static OffMode prev_state = OFF_NOTHING;


    switch(g_btn_adc_result){
    case (OFF_POWERON):
    {
        LCD1602_clear();
        LCD1602_1stLine();
        sprintf(str, "POWER ON");
        LCD1602_print(str);
        LCD1602_loading();
        if(prev_state != OFF_POWERON){
            prev_state = OFF_POWERON;
            //SPI송신
            //화면전환
            g_current_ctrl_state = CTRL_ON;

        }
        break;
    }
    case (OFF_FIND):
    {
        LCD1602_clear();
        LCD1602_1stLine();
        sprintf(str, "ALERT MY CAR");
        LCD1602_print(str);
        LCD1602_loading();
        if(prev_state != OFF_FIND){
            prev_state = OFF_FIND;
            //SPI송신

        }
        //SPI송신
        break;
    }

    // **********OTA시 활성화*********************//
    case (OFF_AUTO_EXIT):
    {
        LCD1602_clear();
        if(g_current_ota_update == OTA_UPDATED)
        {

            LCD1602_1stLine();
            sprintf(str, "LEAVING MY CAR");
            LCD1602_print(str);
            LCD1602_2ndLine();
            LCD1602_loading();
            if(prev_state != OFF_AUTO_EXIT){
                prev_state = OFF_AUTO_EXIT;

                //SPI송신

            }
        }
        else
        {
            LCD1602_1stLine();
            sprintf(str, "DO SUBSCRIBE TO");
            LCD1602_print(str);
            LCD1602_2ndLine();
            sprintf(str, "USE AUTO LEAVING");
            LCD1602_print(str);
            LCD1602_loading();

        }
        break;
    }


    //******************************************//
    default :
    {
//        sprintf(str, "");
        prev_state = OFF_NOTHING;
    }
    }
//    LCD1602_print(str);
}

void Control_Current_State()
{
    switch(g_current_ctrl_state){
    case (CTRL_OFF):
    {
        Show_Off_State();
        break;
    }
    case (CTRL_ON):
    {
        Show_Drive_State();
        break;
    }
    case (CTRL_OTA):
    {
        Show_OTA_State();
        break;
    }
    }
}

void init_Controller()
{
    ControllerState g_current_ctrl_state = CTRL_OFF;
}

/*
 * @brief  button 데이터(A8, SAR4.7)초기화 함수
 */
void init_Btn_Adc(void)
{
    uint32    chnIx = 7;

    /* VADC Configuration */

    /* create configuration */
    IfxVadc_Adc_Config adcConfig;
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);

    /* initialize module */
    IfxVadc_Adc_initModule(&g_LCD_Btn.vadc, &adcConfig);

    /* create group config */
    IfxVadc_Adc_GroupConfig adcGroupConfig;
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &g_LCD_Btn.vadc);

    /* with group 0 */
    adcGroupConfig.groupId = IfxVadc_GroupId_4;
    adcGroupConfig.master  = adcGroupConfig.groupId;

    /* enable scan source */
    adcGroupConfig.arbiter.requestSlotScanEnabled = TRUE;

    /* enable auto scan */
    adcGroupConfig.scanRequest.autoscanEnabled = TRUE;

    /* enable all gates in "always" mode (no edge detection) */
    adcGroupConfig.scanRequest.triggerConfig.gatingMode =
                                    IfxVadc_GatingMode_always;

    /* initialize the group */
    /*IfxVadc_Adc_Group adcGroup;*/    //declared globally
    IfxVadc_Adc_initGroup(&g_LCD_Btn.adcGroup, &adcGroupConfig);

    /*channel init*/
    IfxVadc_Adc_initChannelConfig(&adc_channel_config_btn[chnIx],
                                            &g_LCD_Btn.adcGroup);

    adc_channel_config_btn[chnIx].channelId      =
            (IfxVadc_ChannelId)(chnIx);
    adc_channel_config_btn[chnIx].resultRegister =
            (IfxVadc_ChannelResult)(chnIx); /* use dedicated result register */

    /* initialize the channel */
    IfxVadc_Adc_initChannel(&adc_channel_btn[chnIx],
                    &adc_channel_config_btn[chnIx]);

    /* add to scan */
    unsigned channels = (1 << adc_channel_config_btn[chnIx].channelId);
    unsigned mask     = channels;
    IfxVadc_Adc_setScan(&g_LCD_Btn.adcGroup, channels, mask);

}


/*
 * @brief  adc 변환을 시작하는 함수
 */
void start_btn_conversion(void)
{
    /* start autoscan */
    IfxVadc_Adc_startScan(&g_LCD_Btn.adcGroup);
}


/*
 * @brief  센서 데이터를 읽어오는 함수
 * @return uint32: adc 결과값
 */
uint32 obtain_btn_data(void)
{
    uint32    chnIx =7;
    Ifx_VADC_RES conversionResult; /* wait for valid result */

    /* check results */
    do
    {
        conversionResult = IfxVadc_Adc_getResult(&adc_channel_btn[chnIx]);
    } while (!conversionResult.B.VF);

    adc_result_btn[chnIx] = conversionResult.B.RESULT;
    return adc_result_btn[chnIx];
}


/*
 * @brief  디버깅을 위해 adc 글로벌 결과값 출력하는 함수
 * @return uint32: adc 글로벌 결과값
 * @note   get_decibel 함수 동작 이후에 수행해야함
 */
uint32 get_btn_analog_value(void) {
    return g_btn_adc_result;
}


/*
 * @brief  아날로그 결과값을 데시벨로 변환하는 함수
 * @param  analogValue: obtain으로 얻은 adc 결과값
 * @return
 * @note
 */
ButtonState convert(uint32 analogValue) {
    float voltage = analogValue * (5.0 / 4095.0);
    ButtonState BS = BS_NOTHING;
    if(voltage < 0.5)
    {
        BS= BS_UP;
    }

    else if(voltage < 1.0)
    {
        BS= BS_DOWN;
    }

    else if(voltage < 2.0)
    {
        BS= BS_LEFT;
    }

    else if(voltage < 3.0)
    {
        BS= BS_RIGHT;
    }
    else if(voltage < 4.0)
    {
        BS= BS_SELECT;
    }


    return BS;
}


/*
 * @brief  ButtonState를 받아오는 함수
 * @return float: 데시별 결과값
 * @note   2ms 이상의 주기에서 수행해야함
 */
uint8 get_btn_data(void) {
    start_btn_conversion();
    MicroSecDelay(200); // adc 변환 시간 확보
    uint32 adc_result = obtain_btn_data();

    //디버깅을 위한 부분
    g_btn_adc_result = convert(adc_result);

    return 1;
}
/*********************************************************************************************************************/
