/**********************************************************************************************************************
 * \file Controller_Logic.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include <stdio.h>
#include <string.h>
#include <IfxSrc_reg.h>
#include "Common_def.h"
#include "Delay.h"
#include "Message.h"
#include "Data_process.h"
#include "TC275_LCD_16x2.h"
#include "Controller_Logic.h"
#include "ASCLIN_UART.h"
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
Vadc_t g_LCD_Btn;
Vadc_t g_Steering_Wheel;

IfxVadc_Adc_ChannelConfig adc_channel_config_btn[8];
IfxVadc_Adc_Channel   adc_channel_btn[8];
uint32 adc_result_buffer[8] = {0u,};


/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
static char str[20];
ButtonState g_btn_adc_result = BS_NOTHING;
sint8 g_SH_adc_result = 0;
ControllerState g_current_ctrl_state = CTRL_OFF;
OTAUpdateState g_current_ota_update = OTA_UPDATED;

static DriveDir dir_state = DIR_P;


//데이터 무결성 보장을 위해, 통신데이터 저장후 사용



static OUR_signal local_udt_req_sig;
static OUS_signal local_udt_state_sig;
static PS_signal local_prk_status_sig;
static VS_signal local_vhc_status_sig;

/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
static void disableUartRxInterrupt() {
    SRC_ASCLIN0RX.B.SRE = 0;  // ASCLIN0 RX 인터럽트 비활성화
}

static void enableUartRxInterrupt() {
    SRC_ASCLIN0RX.B.SRE = 1;  // ASCLIN0 RX 인터럽트 활성화
}
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void Show_OTA_State()
{
    LCD1602_clear();


    // 첫째 줄 - 코멘트
    LCD1602_1stLine();


    sprintf(str, "SERVICE LOAD");

    LCD1602_print(str);
    LCD1602_loading();


    // 둘째 줄
    LCD1602_2ndLine();

    uint8 ota_pct = 50;


    sprintf(str, "OTA-%02d%%", ota_pct);

    LCD1602_print(str);

    LCD1602_print_percent_img(ota_pct);
}

void Show_Drive_State()
{
    LCD1602_clear();



    static DriveModeState ms_state = MS_AUTO_PARKING;
    static DriveMode prev_state = DRIVE_NOTHING;
    LCD1602_1stLine();

    switch(g_btn_adc_result){
    case (DRIVE_ACCEL):
    {
        //명령송신
        if(dir_state == DIR_D || dir_state == DIR_R){
            msg.move_msg.signal.control_accel = 1;
            msg.move_msg.signal.control_brake = 0;
            sprintf(str, "GOGOGO");

            // 테스트용 ******************** 직접 받아서 할땐 지워야함!!!
            #ifdef BEFORE_RECEIVE_TEST
            msg.cgw_vhc_status_msg.signal.vehicle_velocity++;
            #endif
        }
        else if (dir_state == DIR_P)
        {
            sprintf(str, "CHANGE DR MODE!");
        }

        prev_state = DRIVE_ACCEL;
        break;
    }
    case (DRIVE_BRAKE):
    {
        //명령송신
        if(dir_state == DIR_D || dir_state == DIR_R){
            msg.move_msg.signal.control_accel = 0;
            msg.move_msg.signal.control_brake = 1;
            sprintf(str, "SLOW SLOW");
            // 테스트용 ******************** 직접 받아서 할땐 지워야함!!!
            #ifdef BEFORE_RECEIVE_TEST
            if (msg.cgw_vhc_status_msg.signal.vehicle_velocity >0)
                msg.cgw_vhc_status_msg.signal.vehicle_velocity--;
            #endif

        }
        else if (dir_state == DIR_P)
        {
            sprintf(str, "CHANGE DR MODE!");
        }

        prev_state = DRIVE_BRAKE;
        break;
    }
    case (DRIVE_POWEROFF):
    {
        if(prev_state != DRIVE_POWEROFF){
            prev_state = DRIVE_POWEROFF;
            //차량 모드가 Parking일때만 전원 종료 수행
            if(dir_state == DIR_P)
            {
                g_current_ctrl_state = CTRL_OFF;
                // 명령 송신
                msg.engine_msg.signal.control_engine = g_current_ctrl_state;
#ifndef PERIOD_VER
                Command[ORDER_ENGINE]();
#endif
                LCD1602_clear();
                LCD1602_1stLine();
                sprintf(str, "POWER OFF");
                LCD1602_print(str);
                LCD1602_loading();
            }
            else if(local_vhc_status_sig.vehicle_velocity == 0)
            {
                dir_state = DIR_P;
                //msg.move_msg.signal.control_transmission = dir_state;

                LCD1602_clear();
                LCD1602_1stLine();
                sprintf(str, "PARKING");
                LCD1602_print(str);
                LCD1602_loading();



            }

        }
        // 위 조건을 만족하지 못하고 나왔다면, 속도를 0으로 하라는 메시지 출력
        if(local_vhc_status_sig.vehicle_velocity != 0){
            LCD1602_clear();
            LCD1602_1stLine();
            sprintf(str, "SET SPEED TO 0!!");
            LCD1602_print(str);
        }
        break;
    }
    case (DRIVE_MODE):
    {
        sprintf(str, "DIRECTION CHANGE");

        if(prev_state != DRIVE_MODE){
            prev_state = DRIVE_MODE;

            if(dir_state == DIR_D)
            {
                dir_state = DIR_R;
            }
            else if(dir_state == DIR_R)
            {

                dir_state = DIR_D;

            }
            else if(dir_state == DIR_P)
            {
                dir_state = DIR_D;
            }
            // 명령 송신
            //msg.move_msg.signal.control_transmission = dir_state;
        }
        break;
    }
    // **********OTA시 활성화*********************//
    case (DRIVE_SERVICE):
    {
        LCD1602_clear();
        if(g_current_ota_update == OTA_UPDATED)
        {
            if(prev_state != DRIVE_SERVICE){
                prev_state = DRIVE_SERVICE;
                if((dir_state == DIR_D || dir_state == DIR_R) &&
                        (local_vhc_status_sig.vehicle_velocity == 0))
                {

                    ms_state = MS_AUTO_PARKING;
                    dir_state = DIR_P;

                    //명령 송신 아래 로딩함수 때문에, 바로 전송
                    msg.auto_park_req_msg.signal.auto_parking = DO_AUTO_PARKING;
#ifndef PERIOD_VER
                    Command[ORDER_AUTO_PRK_REQ]();
#endif

                    LCD1602_1stLine();
                    sprintf(str, "AUTO PARKING");
                    LCD1602_print(str);
                    LCD1602_loading();


                    //화면 전환
                    g_current_ctrl_state = CTRL_AUTO_PARKING;

                }
                else if(dir_state == DIR_P)
                {
                    ms_state = MS_DRIVE;
                    dir_state = DIR_D;
#ifdef PERIOD_VER
                    msg.auto_park_req_msg.signal.auto_parking = DO_NOT_AUTO_PARKING;
#endif

#ifndef PERIOD_VER
                    //이벤트 함수라, 굳이 전송 x
//                    msg.auto_park_req_msg.signal.auto_parking = 0;
//                    Command[ORDER_AUTO_PRK_REQ]();
#endif
                    LCD1602_1stLine();
                    sprintf(str, "DRIVING MODE");
                    LCD1602_print(str);
                    LCD1602_loading();
                }
                //명령 송신
                //msg.move_msg.signal.control_transmission = dir_state;

            }
            // 위 조건을 만족하지 못하고 나왔다면, 속도를 0으로 하라는 메시지 출력
            if(local_vhc_status_sig.vehicle_velocity != 0 && dir_state != DIR_P){
                LCD1602_clear();
                LCD1602_1stLine();
                sprintf(str, "SET SPEED TO 0!!");
                LCD1602_print(str);
            }
        }
        else
        {
            LCD1602_1stLine();
            sprintf(str, "DO SUBSCRIBE TO");
            LCD1602_print(str);
            LCD1602_2ndLine();
            sprintf(str, "USE AUTO PARKING");
            LCD1602_print(str);
            LCD1602_loading();

        }



        break;
    }
    //******************************************//
    default :
    {
        sprintf(str, "");
        prev_state = BS_NOTHING;
        msg.move_msg.signal.control_accel = 0;
        msg.move_msg.signal.control_brake = 0;
    }
    }

    LCD1602_print(str);


    LCD1602_2ndLine();
    if(dir_state == DIR_D || dir_state == DIR_R)
    {
        if(dir_state == DIR_D)
        {
            sprintf(str, "D %d",local_vhc_status_sig.vehicle_velocity);
        }
        else if(dir_state == DIR_R)
        {
            sprintf(str, "R %d",local_vhc_status_sig.vehicle_velocity);
        }
        LCD1602_print(str);

        LCD1602_setCursor(2, 7);
        LCD1602_print("DRIVE MODE");

    }
    else if(dir_state == DIR_P)
    {
        sprintf(str, "P %d PARKING MODE",local_vhc_status_sig.vehicle_velocity);
        LCD1602_print(str);
    }

}

void Show_Off_State()
{
    LCD1602_clear();


    // 첫째 줄 - 코멘트
    LCD1602_1stLine();



    LCD1602_print("PWR");
    LCD1602_print_picture(PIC_ROTATED_LINE);
    LCD1602_print("VEHICLE FIND");


    // 둘째 줄
    LCD1602_2ndLine();

    LCD1602_print_picture(PIC_LEFT_DOWN_ARROW);

    LCD1602_print("ON");

    LCD1602_print_picture(PIC_DOWN_ARROW);
    LCD1602_print(" ");
    LCD1602_print_picture(PIC_DOWN_ARROW);

    LCD1602_print("AUTO LEAVE");





    static OffMode prev_state = OFF_NOTHING;


    switch(g_btn_adc_result){
    case (OFF_POWERON):
    {
        LCD1602_clear();


        LCD1602_1stLine();
        sprintf(str, "POWER ON");
        LCD1602_print(str);
        LCD1602_loading();
        if(prev_state != OFF_POWERON){
            prev_state = OFF_POWERON;
            //화면전환
            g_current_ctrl_state = CTRL_ON;

            //명령 송신
            msg.engine_msg.signal.control_engine = g_current_ctrl_state;

#ifndef PERIOD_VER
            Command[ORDER_ENGINE]();
#endif
            //********* 시동키면 P로 수정해야할수도 *************
            msg.move_msg.signal.control_transmission = DIR_P;



        }
        break;
    }
    case (OFF_FIND):
    {
        LCD1602_clear();

        if(prev_state != OFF_FIND){
            prev_state = OFF_FIND;
            //SPI송신
            msg.off_req_msg.signal.alert_request = 1;
#ifndef PERIOD_VER
            Command[ORDER_OFF_REQ]();
            // 1 신호만 보내고 기본신호 0으로 변경,
            // Msg에 두개의 signal이 있어서 변경안해놓으면 신호겹칠듯
            msg.off_req_msg.signal.alert_request = 0;
#endif



        }
        LCD1602_1stLine();
        sprintf(str, "ALERT MY CAR");
        LCD1602_print(str);
        LCD1602_loading();

        break;
    }

    // **********OTA시 활성화*********************//
    case (OFF_AUTO_EXIT):
    {
        LCD1602_clear();


        if(g_current_ota_update == OTA_UPDATED)
        {
            if(prev_state != OFF_AUTO_EXIT){
                prev_state = OFF_AUTO_EXIT;

                //SPI송신
                msg.off_req_msg.signal.auto_exit_request = 1;
#ifndef PERIOD_VER
                Command[ORDER_OFF_REQ]();
                // 1 신호만 보내고 기본신호 0으로 변경,
                // Msg에 두개의 signal이 있어서 변경안해놓으면 신호겹칠듯
                msg.off_req_msg.signal.auto_exit_request = 0;
#endif

            }
            LCD1602_1stLine();
            sprintf(str, "LEAVING MY CAR");
            LCD1602_print(str);
            LCD1602_2ndLine();
            LCD1602_loading();
        }
        else
        {
            LCD1602_1stLine();
            sprintf(str, "DO SUBSCRIBE TO");
            LCD1602_print(str);
            LCD1602_2ndLine();
            sprintf(str, "USE AUTO LEAVING");
            LCD1602_print(str);
            LCD1602_loading();

        }
        break;
    }


    //******************************************//
    default :
    {
//        sprintf(str, "");
#ifdef PERIOD_VER
        //2턴 지나고 나서 0으로 바꿈
        if(prev_state == OFF_NOTHING){
            msg.off_req_msg.signal.alert_request = 0;
            msg.off_req_msg.signal.auto_exit_request = 0;
        }
#endif
        prev_state = OFF_NOTHING;
    }
    }
//    LCD1602_print(str);
}

void Show_Auto_Parking_State()
{
    LCD1602_clear();


    // 첫째 줄 - 코멘트
    LCD1602_1stLine();


    static ParkingMode prev_state = PARK_NOTHING;


    // 테스트용 ******************** 직접 받아서 할땐 지워야함!!!
    #ifdef BEFORE_RECEIVE_TEST
//    msg.cgw_vhc_status_msg.signal.vehicle_transmission = DIR_D;
    #endif

    switch(g_btn_adc_result){
    case (PARK_BC_BRAKE):
    {
        // parking중에도 Brake가 동작하도록
        //명령송신
        msg.move_msg.signal.control_accel = 0;
        msg.move_msg.signal.control_brake = 1;
        LCD1602_print("PAUSE PARKING");
        LCD1602_2ndLine();
        LCD1602_loading();
        // 테스트용 ******************** 직접 받아서 할땐 지워야함!!!
        #ifdef BEFORE_RECEIVE_TEST
        if (msg.cgw_vhc_status_msg.signal.vehicle_velocity >0)
            msg.cgw_vhc_status_msg.signal.vehicle_velocity--;
        #endif

//        dir_state = local_vhc_status_sig.vehicle_transmission;
        g_current_ctrl_state = CTRL_ON;

        break;
    }

    default :
    {
//        sprintf(str, "");
//        LCD1602_print(str);
    }
    }

    // 테스트용 ******************** 직접 받아서 할땐 지워야함!!!
#ifdef BEFORE_RECEIVE_TEST
    msg.cgw_prk_status_msg.signal.parking_status = ((uint8)msg.move_msg.signal.control_steering_angle)>=45 ? 3 : ((uint8)msg.move_msg.signal.control_steering_angle)%3;
#endif

    switch (local_prk_status_sig.parking_status)
    {
    case (PARK_SEARCHING) :
    {

        LCD1602_print("SEARCHING EMPTY");
        LCD1602_2ndLine();
        LCD1602_print("SPACE");
        static int target = 0;
        for(int i =0 ; i< target; i++)
        {
            LCD1602_print(".");
        }
        target++;
        if(target == 16) target =0;
        prev_state = PARK_SEARCHING;
        break;

    }
    case (PARK_ING_D) :
    {

#ifdef BEFORE_RECEIVE_TEST
        msg.cgw_vhc_status_msg.signal.vehicle_transmission = DIR_D;
#endif
        LCD1602_print("PARKING IN DRIVE");
        LCD1602_2ndLine();
        static int target = 0;
        for(int i =0 ; i< target; i++)
        {
            LCD1602_print(".");
        }
        target++;
        if(target == 16) target =0;

        prev_state = PARK_ING_D;
        break;
    }
    case (PARK_ING_R) :
    {
#ifdef BEFORE_RECEIVE_TEST
        msg.cgw_vhc_status_msg.signal.vehicle_transmission = DIR_R;
#endif
        LCD1602_print("PARKING IN REVRS");
        LCD1602_2ndLine();
        static int target = 0;
        for(int i =0 ; i< target; i++)
        {
            LCD1602_print(".");
        }
        target++;
        if(target == 16) target =0;

        prev_state = PARK_ING_R;
        break;
    }
    case (PARK_FINISH) :
    {
#ifdef BEFORE_RECEIVE_TEST
        msg.cgw_vhc_status_msg.signal.vehicle_transmission = DIR_P;
#endif
        //msg.move_msg.signal.control_transmission = dir_state;

        if(prev_state == PARK_FINISH){
         // Parking 기어 반영을 위함, 한번 더 수행 후 화면전환
            LCD1602_print("PARKING FINISHED");
            LCD1602_2ndLine();
            LCD1602_loading();
            g_current_ctrl_state = CTRL_ON;

        }
        prev_state = PARK_FINISH;
        break;
    }
    default :
    {

    }

    }
    dir_state = local_vhc_status_sig.vehicle_transmission;

}

void Control_Current_State()
{
    {
        msg.move_msg.signal.control_transmission = dir_state;
    }
    {
        // TASK마다 수신 값 최신화
        // 데이터 무결성을 위해, 값 최신화 중 uart수신 인터럽트 비활성화
        disableUartRxInterrupt();
        memcpy(&local_udt_req_sig, &msg.cgw_ota_udt_req_msg.signal,sizeof(local_udt_req_sig));
        memcpy(&local_udt_state_sig, &msg.cgw_ota_udt_state_msg.signal,sizeof(local_udt_state_sig));
        memcpy(&local_prk_status_sig, &msg.cgw_prk_status_msg.signal,sizeof(local_prk_status_sig));
        memcpy(&local_vhc_status_sig, &msg.cgw_vhc_status_msg.signal,sizeof(local_vhc_status_sig));
        enableUartRxInterrupt();
    }

    {
        // 제어버튼, 조향 데이터 최신화
        get_btn_data();
    }


    switch(g_current_ctrl_state){
    case (CTRL_OFF):
    {
        Show_Off_State();
        break;
    }
    case (CTRL_ON):
    {
        Show_Drive_State();
        break;
    }
    case (CTRL_OTA):
    {
        Show_OTA_State();
        break;
    }
    case (CTRL_AUTO_PARKING):
    {
        Show_Auto_Parking_State();
        break;
    }
    default :
    {
        //LCD 테스트 출력 공간
        LCD1602_clear();
        get_SH_data();
    }
    }
}

void init_Controller()
{
    //초기화면 설정칸
    g_current_ctrl_state = CTRL_OFF;
}

/*
 * @brief  button 데이터(A8, SAR4.6)초기화 함수
 */

static void init_Vadc_Config(Vadc_t * Vadc_val){

    /* VADC Configuration */

    /* create configuration */
    IfxVadc_Adc_Config adcConfig;
    IfxVadc_Adc_initModuleConfig(&adcConfig, &MODULE_VADC);

    /* initialize module */
    IfxVadc_Adc_initModule(&Vadc_val->vadc, &adcConfig);

    /* create group config */
    IfxVadc_Adc_GroupConfig adcGroupConfig;
    IfxVadc_Adc_initGroupConfig(&adcGroupConfig, &Vadc_val->vadc);

    /* with group  */
    adcGroupConfig.groupId = Vadc_val->adcGroupId;
    adcGroupConfig.master  = adcGroupConfig.groupId;

    /* enable scan source */
    adcGroupConfig.arbiter.requestSlotScanEnabled = TRUE;

    /* enable auto scan */
    adcGroupConfig.scanRequest.autoscanEnabled = TRUE;

    /* enable all gates in "always" mode (no edge detection) */
    adcGroupConfig.scanRequest.triggerConfig.gatingMode =
                                    IfxVadc_GatingMode_always;

    /* initialize the group */
    /*IfxVadc_Adc_Group adcGroup;*/    //declared globally
    IfxVadc_Adc_initGroup(&Vadc_val->adcGroup, &adcGroupConfig);

    /*channel init*/
    IfxVadc_Adc_initChannelConfig(&adc_channel_config_btn[Vadc_val->chnIx],
                                            &Vadc_val->adcGroup);

    adc_channel_config_btn[Vadc_val->chnIx].channelId      =
            (IfxVadc_ChannelId)(Vadc_val->chnIx);
    adc_channel_config_btn[Vadc_val->chnIx].resultRegister =
            (IfxVadc_ChannelResult)(Vadc_val->chnIx); /* use dedicated result register */

    /* initialize the channel */
    IfxVadc_Adc_initChannel(&adc_channel_btn[Vadc_val->chnIx],
                    &adc_channel_config_btn[Vadc_val->chnIx]);

    /* add to scan */
    unsigned channels = (1 << adc_channel_config_btn[Vadc_val->chnIx].channelId);
    unsigned mask     = channels;
    IfxVadc_Adc_setScan(&Vadc_val->adcGroup, channels, mask);
}

void init_Steering_Wheel(){
    // 4_6
    g_Steering_Wheel.adcGroupId = IfxVadc_GroupId_4;
    g_Steering_Wheel.chnIx = 6;
    init_Vadc_Config(&g_Steering_Wheel);

}
/*
 * @brief  button 데이터(A8, SAR4.7)초기화 함수
 */
void init_Btn_Adc(void)
{
    //4_7
    g_LCD_Btn.adcGroupId = IfxVadc_GroupId_4;
    g_LCD_Btn.chnIx = 7;
    init_Vadc_Config(&g_LCD_Btn);
}


/*
 * @brief  adc 변환을 시작하는 함수
 */
void start_btn_conversion(void)
{
    /* start autoscan */
    IfxVadc_Adc_startScan(&g_LCD_Btn.adcGroup);
}


static sint8 mapValue(float input, float in_min, float in_max, float out_min, float out_max) {
    return (sint8)((input - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);
}

/*
 * @brief  센서 데이터를 읽어오는 함수
 * @return uint32: adc 결과값
 */
static sint8 convert_SH_data(uint32 analogValue) {
    float voltage = analogValue * (5.0 / 4095.0);

    sint8 steeringAngle = mapValue(voltage, 0.0, 5.0, -45, 45);

//    sprintf(str,"%d / %.2f",steeringAngle,voltage);
//    LCD1602_print(str);

    return steeringAngle;
}

uint8 get_SH_data(void)
{
//    start_btn_conversion(); // 같은 채널임
//    MicroSecDelay(200); // adc 변환 시간 확보
    uint32 adc_result =  obtain_Vadc_data(g_Steering_Wheel.chnIx);

    //디버깅을 위한 부분
    g_SH_adc_result = convert_SH_data(adc_result);
    if(g_SH_adc_result <= 45)
        msg.move_msg.signal.control_steering_angle = g_SH_adc_result;
    return 1;
}


uint32 obtain_Vadc_data(uint32 chnIx)
{

    Ifx_VADC_RES conversionResult; /* wait for valid result */

    /* check results */
    do
    {
        conversionResult = IfxVadc_Adc_getResult(&adc_channel_btn[chnIx]);
    } while (!conversionResult.B.VF);

    adc_result_buffer[chnIx] = conversionResult.B.RESULT;
    return adc_result_buffer[chnIx];
}



/*
 * @brief  아날로그 결과값을 데시벨로 변환하는 함수
 * @param  analogValue: obtain으로 얻은 adc 결과값
 * @return
 * @note
 */
static ButtonState convert_btn_data(uint32 analogValue) {
    float voltage = analogValue * (5.0 / 4095.0);
    ButtonState BS = BS_NOTHING;
    if(voltage < 0.5)
    {
        BS= BS_UP;
    }

    else if(voltage < 1.0)
    {
        BS= BS_DOWN;
    }

    else if(voltage < 2.0)
    {
        BS= BS_LEFT;
    }

    else if(voltage < 3.0)
    {
        BS= BS_RIGHT;
    }
    else if(voltage < 4.0)
    {
        BS= BS_SELECT;
    }


    return BS;
}


/*
 * @brief  ButtonState를 받아오는 함수
 * @return float: 데시별 결과값
 * @note   2ms 이상의 주기에서 수행해야함
 */
uint8 get_btn_data(void) {
    start_btn_conversion();
    MicroSecDelay(200); // adc 변환 시간 확보
    uint32 adc_result = obtain_Vadc_data(g_LCD_Btn.chnIx);

    //디버깅을 위한 부분
    g_btn_adc_result = convert_btn_data(adc_result);

    //btn 인풋 받을때 같이 받기
    get_SH_data();
    return 1;
}
/*********************************************************************************************************************/
