/**********************************************************************************************************************
 * \file data_process.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "data_process.h"

#include "Message.h"

#include <string.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void process_send_datas(uint8 *txbuf, uint8* rxbuf){
    static sint8 data =-64;
    static uint8 num = 0;
    uint8 dlc = sizeof(msg.move_msg.signal);
    //    uint8 dlc =  getMoveSignalSize();
    msg.move_msg.msgId = ID_CTRL_MOVE_MSG;
    msg.move_msg.signal.control_accel = num++;
    msg.move_msg.signal.control_brake = num+1;
    msg.move_msg.signal.control_steering_angle = data++;
    msg.move_msg.signal.control_transmission = num;

//    no_padding(msg.move_msg);

     // 올바른 DLC 크기 계산


    //    uint8 serialized_signal[3];
    //    serializeMoveSignal(&msg.move_msg.signal, serialized_signal);
    //    structToByteArray(&g_qspi.spiBuffers.spiMasterTxBuffer[1],&msg.move_msg,sizeof(msg.move_msg));
    txbuf[0] = dlc;
    txbuf[1] = msg.move_msg.msgId;
    memcpy(&txbuf[2], &msg.move_msg.signal, dlc);
}
/*********************************************************************************************************************/
