/**********************************************************************************************************************
 * \file Data_process.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Data_process.h"
#include "ASCLIN_Shell_UART.h"
#include "Message.h"
#include "ASCLIN_UART.h"

#include <string.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
#define BUF_SIZE 32
#define DEBUG_PRINT
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
Commandfp Command[] = {
    Engine_Command,          // ORDER_ENGINE
    Move_Command,            // ORDER_MOVE
    APR_Command,             // ORDER_AUTO_PRK_REQ
    OUC_Command,             // ORDER_OTA_UDT_CFM
    OR_Command,              // ORDER_OFF_REQ
    RCV_Command,             //ORDER_RECEIVE
};


/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void Engine_Command(void)
{
    uint8 txData[BUF_SIZE];
    sint16 dlc = sizeof(msg.engine_msg.signal);
    msg.engine_msg.msgId = ID_ENGINE_MSG;
    txData[0] = (uint8) dlc;
    txData[1] = msg.engine_msg.msgId;
    memcpy(&txData[2], &msg.engine_msg.signal, dlc);

    Send_Message(txData,dlc+2);
}
void Move_Command(void)
{
    uint8 txData[BUF_SIZE];
    sint16 dlc = sizeof(msg.move_msg.signal);
    msg.move_msg.msgId = ID_MOVE_MSG;
    txData[0] = (uint8) dlc;
    txData[1] = msg.move_msg.msgId;


    memcpy(&txData[2], &msg.move_msg.signal, dlc);

    Send_Message(txData,dlc+2);

}

void APR_Command(){
    uint8 txData[BUF_SIZE];
    sint16 dlc = sizeof(msg.auto_park_req_msg.signal);
    msg.auto_park_req_msg.msgId = ID_AUTO_PARK_REQ_MSG;
    txData[0] = (uint8) dlc;
    txData[1] = msg.auto_park_req_msg.msgId;
    memcpy(&txData[2], &msg.auto_park_req_msg.signal, dlc);

    Send_Message(txData,dlc+2);
}


void OUC_Command(){
    uint8 txData[BUF_SIZE];
    sint16 dlc = sizeof(msg.ota_udt_cfm_msg.signal);
    msg.ota_udt_cfm_msg.msgId = ID_OTA_UDT_CFM_MSG;
    txData[0] = (uint8) dlc;
    txData[1] = msg.ota_udt_cfm_msg.msgId;
    memcpy(&txData[2], &msg.ota_udt_cfm_msg.signal, dlc);

    Send_Message(txData,dlc+2);
}

void OR_Command(){
    uint8 txData[BUF_SIZE];
    sint16 dlc = sizeof(msg.off_req_msg.signal);
    msg.off_req_msg.msgId = ID_OFF_REQ_MSG;
    txData[0] = (uint8) dlc;
    txData[1] = msg.off_req_msg.msgId;
    memcpy(&txData[2], &msg.off_req_msg.signal, dlc);

    Send_Message(txData,dlc+2);
}

void RCV_Command(void)
{

    uint8 id = g_rxData[0];
//    for(int i =0; i< g_count-1;i++)
//        myprintf("%d : 0X%02X\t",i, g_rxData[i]);
//    myprintf("\n\r");
    switch(id)
    {
        case (ID_CGW_OTA_UDT_REQ_MSG):
        {
            msg.cgw_ota_udt_req_msg.msgId = ID_CGW_OTA_UDT_REQ_MSG;
            memcpy(&msg.cgw_ota_udt_req_msg.signal, &g_rxData[1], g_rcv_size);
#ifdef DEBUG_PRINT
            myprintf("ID : 0X%02X ota_update_request : %u\n\r",
                    msg.cgw_ota_udt_req_msg.msgId,
                    msg.cgw_ota_udt_req_msg.signal.ota_update_request);
#endif
            break;

        }
        case (ID_CGW_OTA_UDT_STATE_MSG):
        {
            msg.cgw_ota_udt_state_msg.msgId = ID_CGW_OTA_UDT_STATE_MSG;
            memcpy(&msg.cgw_ota_udt_state_msg.signal, &g_rxData[1], g_rcv_size);
#ifdef DEBUG_PRINT
            myprintf("ID : 0X%02X ota_update_progress : %u\n\r",
                    msg.cgw_ota_udt_state_msg.msgId,
                    msg.cgw_ota_udt_state_msg.signal.ota_update_progress);
#endif
            break;

        }
        case (ID_CGW_PRK_STATUS_MSG):
        {
            msg.cgw_prk_status_msg.msgId = ID_CGW_PRK_STATUS_MSG;
            memcpy(&msg.cgw_prk_status_msg.signal, &g_rxData[1], g_rcv_size);
#ifdef DEBUG_PRINT
            myprintf("ID : 0X%02X parking_status : %u\n\r",
                    msg.cgw_prk_status_msg.msgId,
                    msg.cgw_prk_status_msg.signal.parking_status);
#endif
            break;

        }
        case (ID_CGW_VHC_STATUS_MSG):
        {
            msg.cgw_vhc_status_msg.msgId = ID_CGW_VHC_STATUS_MSG;
            memcpy(&msg.cgw_vhc_status_msg.signal, &g_rxData[1], g_rcv_size);
#ifdef DEBUG_PRINT
            myprintf("ID : 0X%02X vehicle_velocity %u / vehicle_steering_angle : %d / vehicle_transmission %u  \n\r",
                    msg.cgw_vhc_status_msg.msgId,
                    msg.cgw_vhc_status_msg.signal.vehicle_velocity,
                    msg.cgw_vhc_status_msg.signal.vehicle_steering_angle,
                    msg.cgw_vhc_status_msg.signal.vehicle_transmission
                    );
#endif
            break;

        }
        default:
        {
            myprintf(" 수신 FAIL\n\r");
        }
    }



}

void Test_Command(void)
{

}

/*********************************************************************************************************************/
