/**********************************************************************************************************************
 * \file Message.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
#include "Message.h"
#include <string.h>
#include <stdint.h>
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
Message msg;
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
void structToByteArray(void *certain_msg, uint8 *buffer, unsigned long long size) {
    memcpy(buffer, certain_msg, size);
}

// 바이트 배열 → 구조체 복원 함수

void byteArrayToStruct(uint8 *buffer, void *certain_msg, unsigned long long size) {
    memcpy(certain_msg, buffer, size);
}



//// 패킹된 데이터를 저장할 구조체
//typedef struct {
//    uint8 bytes[4];  // 11비트 총 사용 (2바이트 필요)
//} packed_data;
//
//// 원본 데이터 설정/가져오기 위한 매크로
//#define GET_BIT(data, pos) (((data) >> (pos)) & 0x01)
//#define SET_BIT(data, pos, val) ((data) = ((data) & ~(1UL << (pos))) | ((val) << (pos)))
//
//// 비트 패킹 함수
//packed_data no_padding(const CTRL_Move *msg) {
//    packed_data result = {0};
//
//    result[1] = msg->msgId;
//
//    // accel [0:0]
//    SET_BIT(result.bytes[2], 0, msg->signal.control_accel);
//
//    // brake [1:1]
//    SET_BIT(result.bytes[2], 1, msg->signal.control_brake);
//
//    // steering_angle [8:2] (7bits)
//    uint8_t steering = (uint8_t)(msg->signal.control_steering_angle & 0x7F);
//    result.bytes[2] |= (steering << 2);
//    result.bytes[3] |= (steering >> 6);
//
//    // transmission [10:9] (2bits)
//    result.bytes[3] |= ((msg->signal.control_transmission & 0x03) << 1);
//
//    return result;
//}
//
//// 패킹된 데이터를 원래 구조체로 변환
//CTRL_Move unpack_data(packed_data packed) {
//    CTRL_Move msg = {0};
//
//    // accel [0:0]
//    msg.signal.control_accel = GET_BIT(packed.bytes[2], 0);
//
//    // brake [1:1]
//    msg.signal.control_brake = GET_BIT(packed.bytes[0], 1);
//
//    // steering_angle [8:2] (7bits)
//    msg.signal.control_steering_angle = (sint8)(
//        ((packed.bytes[0] >> 2) & 0x3F) |  // 하위 6비트
//        ((packed.bytes[1] & 0x01) << 6)     // 최상위 1비트
//    );
//
//    // transmission [10:9] (2bits)
//    msg.signal.control_transmission = (packed.bytes[1] >> 1) & 0x03;
//
//    return msg;
//}
//
//// 패킹된 데이터 전송을 위한 헬퍼 함수
//void send_packed_data(packed_data data) {
//    // 여기에 실제 전송 코드 구현
//    // 예: UART나 CAN으로 data.bytes 전송
//}

/*********************************************************************************************************************/
